# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    # Build docker
    - name: Build docker
      run: docker build --no-cache -t hello-docker .

    # Run docker
    - name: Run docker
      run: docker run -d hello-docker

    # Check cgroup
    - name: Check cgroup
      run: ls /sys/fs/cgroup/memory

    # Check cgroup via script
    - name: Check cgroup via script
      run: ./myscript.sh

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: list.txt
